/*
Auto-generated by: https://github.com/OmnomnomTee/gltfvue
Command: npx gltfvue@0.1.0 public/stylized_car/scene.gltf 
Author: Split Studios (https://sketchfab.com/splitcg)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/stylized-car-0323feeb81e84e67a13acc964b6c609b
Title: Stylized Car
*/
<script setup lang="ts">
import { useGLTF } from '@tresjs/cientos'

const { nodes, materials } = await useGLTF('/stylized_car/scene.gltf')

// Fix unlit materials: Apply emissive textures to base color for proper display
import { TextureLoader } from 'three'
const textureLoader = new TextureLoader()

materials.Ground.color.setRGB(1, 1, 1)
materials.body.color.setRGB(1, 1, 1)
const body_map = textureLoader.load('/stylized_car/textures/body_emissive.png')
body_map.flipY = false
materials.body.map = body_map
materials.wheels_left.color.setRGB(1, 1, 1)
const wheels_left_map = textureLoader.load('/stylized_car/textures/wheels_left_emissive.png')
wheels_left_map.flipY = false
materials.wheels_left.map = wheels_left_map
materials.wheels_right.color.setRGB(1, 1, 1)
const wheels_right_map = textureLoader.load('/stylized_car/textures/wheels_right_emissive.png')
wheels_right_map.flipY = false
materials.wheels_right.map = wheels_right_map

// Mark materials as needing update
Object.values(materials).forEach(mat => mat.needsUpdate = true)

</script>

<template>
  <TresGroup>
<TresMesh :geometry="nodes.Plane007_Ground_0.geometry" :material="materials.Ground" :rotation="[-Math.PI / 2, 0, 0]" :scale="4.244" />
<TresMesh :geometry="nodes.Plane007_body_0.geometry" :material="materials.body" :rotation="[-Math.PI / 2, 0, 0]" :scale="4.244" />
<TresMesh :geometry="nodes.Plane007_wheels_left_0.geometry" :material="materials.wheels_left" :rotation="[-Math.PI / 2, 0, 0]" :scale="4.244" />
<TresMesh :geometry="nodes.Plane007_wheels_right_0.geometry" :material="materials.wheels_right" :rotation="[-Math.PI / 2, 0, 0]" :scale="4.244" />

  </TresGroup>
</template>