/*
Auto-generated by: https://github.com/OmnomnomTee/gltfvue
Command: npx gltfvue@0.1.0 public/stylized_car/scene.gltf --output demo/src/components/Scene.vue --keepgroups --transform 
Files: public/stylized_car/scene.gltf [11.34KB] > /Users/tim/Projects/Personal/gltfvue/demo/src/components/scene-transformed.glb [260.74KB] (-2199%)
Author: Split Studios (https://sketchfab.com/splitcg)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/stylized-car-0323feeb81e84e67a13acc964b6c609b
Title: Stylized Car
*/
<script setup lang="ts">
import { useGLTF } from '@tresjs/cientos'

const { nodes, materials } = await useGLTF('/scene-transformed.glb')

</script>

<template>
  <TresGroup>
<TresGroup >
<TresMesh :geometry="nodes.Plane007_Ground_0.geometry" :material="materials.Ground" :rotation="[-Math.PI / 2, 0, 0]" :scale="4.244" />
<TresMesh :geometry="nodes.Plane007_body_0.geometry" :material="materials.body" :rotation="[-Math.PI / 2, 0, 0]" :scale="4.244" />
<TresMesh :geometry="nodes.Plane007_wheels_left_0.geometry" :material="materials.wheels_left" :rotation="[-Math.PI / 2, 0, 0]" :scale="4.244" />
<TresMesh :geometry="nodes.Plane007_wheels_right_0.geometry" :material="materials.wheels_right" :rotation="[-Math.PI / 2, 0, 0]" :scale="4.244" />
</TresGroup>
  </TresGroup>
</template>